# Generated by Django 4.1.2 on 2022-11-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('abvr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastestLap', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f1site.track')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1site.driver')),
                ('driverTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1site.team')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1site.gp')),
                ('qualifying', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f1site.qualifying')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f1site.race')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='f1site.sprint')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1site.team'),
        ),
    ]
