# Generated by Django 4.1.2 on 2022-11-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non Sprint'), (1, 'Sprint')], default=0),
            preserve_default=False,
        ),
    ]
