# Generated by Django 4.1.2 on 2022-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1site', '0002_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='gp',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non Sprint'), (1, 'Sprint')], default=1),
            preserve_default=False,
        ),
    ]
