# Generated by Django 4.1.2 on 2022-11-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1site', '0003_remove_event_type_gp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
    ]
