# Generated by Django 4.1.2 on 2022-11-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1site', '0005_alter_driver_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='driverTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='f1site.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qualifying',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='f1site.qualifying'),
        ),
        migrations.AlterField(
            model_name='event',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='f1site.race'),
        ),
    ]
