# Generated by Django 4.1.2 on 2022-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1site', '0006_alter_event_driverteam_alter_event_qualifying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='points',
            field=models.FloatField(),
        ),
    ]
